# Generated by Django 4.1 on 2022-10-25 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_pruduct_qty_cart_product_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quqntity',
            new_name='quantity',
        ),
    ]
